spring.application.name=lc-nc-explainable-shap

spring.config.import=optional:file:.env[.properties]

groq.api.key=${GROQ_API_KEY}
groq.base.url=https://api.groq.com/openai/v1/chat/completions

gemini.api.key=${GEMINI_API_KEY}
gemini.base.url=https://generativelanguage.googleapis.com